---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
        name: Check YAML files
  - repo: https://github.com/jumanjihouse/pre-commit-hook-yamlfmt
    rev: 0.1.0
    hooks:
      - id: yamlfmt
        args: [--mapping, '2', --sequence, '4', --offset, '2']
  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.26.3
    hooks:
      - id: yamllint
        name: Lint YAML files
        args: [--format, parsable, --strict, -c=tests/yamllint.yaml]
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.30.0
    hooks:
      - id: markdownlint
  - repo: https://github.com/asottile/reorder_python_imports
    rev: v2.7.1
    hooks:
      - id: reorder-python-imports
  - repo: https://github.com/ambv/black
    rev: 22.1.0
    hooks:
    - id: black
      language_version: python3.9
