---
name: ✨ New Script Request
description: Propose a new NetBox Script or Report
title: "[Script Request]: "
labels: ["script_request"]
body:
  - type: markdown
    attributes:
      value: >
        **NOTE:** This form is only for submitting well-formed proposals to create a NetBox custom script or report.
        If you're trying to solve a problem but can't figure out how, or if
        you still need time to work on the details of a proposed new script, please start a
        [discussion](https://github.com/netbox-community/reports/discussions) instead.
  - type: input
    attributes:
      label: NetBox version
      description: What version of NetBox are you currently running?
      placeholder: v3.1.6
    validations:
      required: true
  - type: dropdown
    attributes:
      label: Request type
      options:
        - New NetBox Custom Script
        - New NetBox Report
    validations:
      required: true
  - type: textarea
    attributes:
      label: Proposed functionality
      description: >
        Describe in detail the new feature or behavior you are proposing. Include any specific introductions
        to work flows, logic, and/or external data sources. The more detail you provide here, the
        greater chance your proposal has of being discussed and taken up by a contributor.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Use case
      description: >
        Explain how creating this script/report would benefit  NetBox users. What need does it address?
    validations:
      required: true
  - type: textarea
    attributes:
      label: External dependencies
      description: >
        List any new dependencies on external libraries or services that this new feature would
        introduce. For example, does the proposal require the installation of a new Python package,
        access to another non-NetBox service?  (Not all new features introduce new dependencies.)
